# Site settings
title: Yifan Liu
email: yifan_liu@brown.edu
url: https://example.github.io
description: "I am a computer science student at Brown University"
keywords: "Computer Science, Brown, Software Engineering, Machine Learning"
skills: ".NET Development - Android Development - Virtual Reality Development"
meta_author: Liu Yifan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Yifan Liu
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Yifan_BIM
  - title: facebook
    url: https://facebook.com
  - title: stack-overflow
    url: http://stackoverflow.com
  - title: bitbucket
    url: http://bitbucket.org/
  - title: github
    url: http://github.com/yifan-liu

# Postal address (add as many lines as necessary)
address:
  - line: Department of Computer Science
  - line: Brown University
  - line: Providence
  - line: Rhode Island, 02906

# Credits content
credits: 'This website is created based on a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>. Big thanks to Start Bootstrap!'

# Build settings
markdown: kramdown
permalink: pretty
